apiVersion: v1
kind: Service
metadata:
  name: cnc-agent-service
  labels:
    app: cnc-agent
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: cnc-agent
  type: LoadBalancer